### ISSUE TITLE
Envoyer projet à Hello@crewz.io

### ISSUE THREAD

**Issue by olivierchatillon** [olivierchatillon/CREWZ#12]
Lorsqu'un nouveau projet est validé, envoyer mail à hello@crewz.io (malvin a les specs de l'email)

**Comment by mmoustai** [comment]
![image](https://user-images.githubusercontent.com/6247743/72655905-bf6e5c00-39eb-11ea-95db-a704b8e2aebd.png)

nouvelle feature à ajouter ?

**Comment by olivierchatillon** [comment]
on parle bien de ça ? 
https://docs.google.com/spreadsheets/d/1Bv0ymaOgFycbZjxfLI4wlJWtY0JZHy9-r4yu0Ue4SVk/edit#gid=0

**Comment by mmoustai** [comment]
Yes !

**Comment by mmoustai** [comment]
@olivierchatillon ^

**Comment by olivierchatillon** [comment]
Je parle d'une notif pour dire qu'il y a un nouveau projet.
