### ISSUE TITLE
Screen 3 lien boutons vidéos

### ISSUE THREAD

**Issue by olivierchatillon** [olivierchatillon/CREWZ#14]
Mettre derriere le bouton www.crewz.io

**Comment by mmoustai** [comment]
Pas compris cette issue @olivierchatillon

**Comment by olivierchatillon** [comment]
sur le dernier screen, il y a un bouton "voir l'experience crewz en vidéo". On peut rediriger soit sur la home soit ici avec 5 vidéos montrant l'expérience crewz https://www.youtube.com/watch?v=g9Ho892Ccag&list=PLMtyz6IPN7BNEUv6EgZIccCxeUL6PxVhI&index=1
