### ISSUE TITLE
Ligne de code apparante

### ISSUE THREAD

**Issue by olivierchatillon** [olivierchatillon/CREWZ#33]
> User clique sur voir la dispo des prix.
une ligne de code s'affiche en haut de l'iframe.
> les bulles qui s'affiche pour rentrer une information dans le champs obligatoire n'est pas centré sur iphone

![Croisiere Catamaran Prix sur mesure](https://user-images.githubusercontent.com/44865632/80864654-5651e200-8c84-11ea-9909-832a10e10717.png)

**Comment by mmoustai** [comment]
@olivierchatillon je n'ai pas réussi a reproduire l'issue. Est-ce que tu peux me dire comment tu as fais ? si c'est toujours d'actualité ?

**Comment by olivierchatillon** [comment]
Oui toujours d'actualité.
Iphone et browser safari. 

Je valide mes dates, appuie sur le bouton "verifier ma dispo..."
L'acran devient blanc. Je remonte et au dessus du titre "à nous de jouer" les 2 lignes de code s'affichent

**Comment by olivierchatillon** [comment]
iphone XR
Version : 13.3.1
Model A2105
Browser safari
